apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: dotnet-basic-lwoxttwf
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/dotnet-basic-lwoxttwf:7e55f68287b1e467cb8f63ad07f57b2901c089f5@sha256:d9daa6e1a9300dbfc0df786728073f0d19f3dc6ee284ff54597a6ca4a45e6fac
          name: container-image
